### ISSUE TITLE
Launcher cannot access file

### ISSUE THREAD

**Issue by TwistedAsylumMC** [MCMrARM/mc-w10-version-launcher#11]
```
App re-register failed:
System.IO.IOException: Access to the path 'C:\Users\sebfa\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at MCLauncher.MainWindow.BackupMinecraftDataForRemoval()
   at MCLauncher.MainWindow.<ReRegisterPackage>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass14_0.<<InvokeLaunch>b__0>d.MoveNext()```

**Comment by Tschipp** [comment]
Same with me

**Comment by MCMrARM** [comment]
Make sure you are in Developer Mode.
If you are, back up your data manually, then uninstall the game and retry.

**Comment by KastetPrivet** [comment]
как сделать резервную копию данных?

**Comment by MCMrARM** [comment]
open `%userprofile%\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftWorlds`

**Comment by CrispyHotdogs** [comment]
how do you back up the data
