### ISSUE TITLE
Deployment failed: Package with Windows Store origin cannot be sideloaded or installed using developer mode option.

### ISSUE THREAD

**Issue by lolpippiou** [MCMrARM/mc-w10-version-launcher#110]
If I try launching any version this error pops up:

![image](https://user-images.githubusercontent.com/50070094/116509518-bb560d00-a8c3-11eb-91db-793a7efd2850.png)

Here's the logs:
```
Registering package
Deployment failed: Package Microsoft.MinecraftUWP_1.16.22101.0_x64__8wekyb3d8bbwe with Windows Store origin cannot be sideloaded or installed using developer mode option.
App re-register failed:
System.Exception: Deployment failed: Package Microsoft.MinecraftUWP_1.16.22101.0_x64__8wekyb3d8bbwe with Windows Store origin cannot be sideloaded or installed using developer mode option.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<DeploymentProgressWrapper>d__21.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<ReRegisterPackage>d__29.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 246
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass20_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 112
```

**Comment by Kerchs5** [comment]
I got the same error

**Comment by lolpippiou** [comment]
I have developer mode enabled and it still says this. I have no idea what it is caused by.

**Comment by SkullNoober** [comment]
Have you solved this issue by any chance? Thanks.

**Comment by Kerchs5** [comment]
I don’t remember how I fixed the problem but it was some developer mode option I think

**Comment by Retapich** [comment]
Good time of day.
I have the same problem even with **developer mode enabled**⤵️
![2023-06-20_210525](https://github.com/MCMrARM/mc-w10-version-launcher/assets/19671942/ecbe7939-ad86-4a76-a828-2268a1e1dc22)
### None of the versions want to install😓

**Yes!** I have received the latest **Win10** system updates and also rebooted the **OS** after changing the mode to developer mode **(I did it 3 times in a row)**
