### ISSUE TITLE
Beta download failed with "Bad updateIdentity" error

### ISSUE THREAD

**Issue by SpiderCorsa** [MCMrARM/mc-w10-version-launcher#120]
The MCLauncher has started without problem, but
I've just trying to download the "1.17.10.22 (Beta)" from the Minecraft Version Manager list,
and it caused a "Bad updateIdentity" error. I also trying to download other versions too, but the problem is the same.

I have the latest Windows10 Bedrock version and it was legally bought from the Microsoft Store.
MCLauncher version: 0.2.1

**log:**
Download start
Waiting for authentication
Authentication complete
Download failed:
System.ArgumentException: Bad updateIdentity
   at MCLauncher.VersionDownloader.<Download>d__6.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\VersionDownloader.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass30_0.<<InvokeDownload>b__1>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 286

**Comment by SpiderCorsa** [comment]
Participate in Beta program is solve this issue for me (more details about the how to are here: https://news.xbox.com/en-us/2020/04/16/minecraft-with-rtx-for-windows-10-beta/ -it may require to install the Xbox Insider Hub app from the Microsoft Store).
BUT I think this exception doesn't looks too nice, maybe the app should be handle it with a proper error message.
Thank you!
