### ISSUE TITLE
Runtime exception when compiling from source

### ISSUE THREAD

**Issue by ambiennt** [MCMrARM/mc-w10-version-launcher#158]
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\...\mc-w10-version-launcher\Debug\imported_versions'.'

```System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'C:\...\mc-w10-version-launcher\Debug\imported_versions'.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at MCLauncher.VersionList.<LoadImported>b__10_0() in C:\...\mc-w10-version-launcher\MCLauncher\VersionList.cs:line 57
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MCLauncher.VersionList.<LoadImported>d__10.MoveNext() in C:\...\mc-w10-version-launcher\MCLauncher\VersionList.cs:line 57
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at MCLauncher.MainWindow.<LoadVersionList>d__15.MoveNext() in C:\...\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 113

  This exception was originally thrown at this call stack:
    [External Code]
    MCLauncher.VersionList.LoadImported.AnonymousMethod__10_0() in VersionList.cs
    [External Code]
    MCLauncher.VersionList.LoadImported() in VersionList.cs
    [External Code]
    MCLauncher.MainWindow.LoadVersionList() in MainWindow.xaml.cs``````
    
    It builds fine but immediately quits both when running in debug and release mode. I have Windows 10 SDK 10.0.19040.0 and .NET Framework 4.7.2 development tools installed. Compiled with visual studio community 2019.

**Comment by dktapps** [comment]
I assume this is fixed by now since appx import has been generally available for the last 4 years and no one else has reported this
