### ISSUE TITLE
app re-register failed please help 

### ISSUE THREAD

**Issue by dragonblack4942** [MCMrARM/mc-w10-version-launcher#198]
System.Exception: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.18.3104.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<DeploymentProgressWrapper>d__24.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<ReRegisterPackage>d__32.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass23_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\project

**Comment by GarudaID** [comment]
> System.Exception: Deployment failed: Deployment of package Microsoft.MinecraftUWP_1.18.3104.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required. at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at MCLauncher.MainWindow.d__24.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 230 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at MCLauncher.MainWindow.d__32.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 324 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at MCLauncher.MainWindow.<>c__DisplayClass23_0.<b__0>d.MoveNext() in C:\Users\dylan-work\Documents\project

You need to enable developer mode in Windows Settings (as stated in release 0.10). Go to Windows settings, then Update & Security, and the second from the bottom on the sidebar should be "For developers". Hop in there and enable developer mode.

**Comment by dragonblack4942** [comment]
Thank you for your suggenstion i will try


Pada tanggal Sel, 21 Jun 2022 19:34, Kaixin Fukada ***@***.***>
menulis:
