### ISSUE TITLE
doesnt work anymore

### ISSUE THREAD

**Issue by GreatNate0509YT** [MCMrARM/mc-w10-version-launcher#220]
gives error and im even launching it with dlls but idk man i can download them i own mc yet no work im trying on mc preveiw heres log .txt Download start
GetDownloadUrl() response for updateIdentity c3b71ea8-b539-4fe5-b68a-5bf3ef4892d2, revision 1:
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
  <s:Header>
    <a:Action s:mustUnderstand="1">http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetExtendedUpdateInfo2Response</a:Action>
    <a:RelatesTo>urn:uuid:5754a03d-d8d5-489f-b24d-efc31b3fd32d</a:RelatesTo>
    <o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <u:Timestamp u:Id="_0">
        <u:Created>2022-08-25T13:57:58.563Z</u:Created>
        <u:Expires>2022-08-25T14:02:58.563Z</u:Expires>
      </u:Timestamp>
    </o:Security>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <GetExtendedUpdateInfo2Response xmlns="http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService">
      <GetExtendedUpdateInfo2Result>
        <FileLocations>
          <FileLocation>
            <FileDigest>hzqY1WiW+MCAepFt5f/ZO1S2+QA=</FileDigest>
            <Url>http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/575928dd-8819-427e-96d4-d2d0b340e93a?P1=1661451999&amp;P2=404&amp;P3=2&amp;P4=MYHea2UxSqouPj%2bNq5zmNN93QMY1e67q%2bNfxpmAeAuXVpqDbyHEi7%2bArQmrb5r5CFS4e16OHZMYt7AD15IT0Qw%3d%3d</Url>
          </FileLocation>
          <FileLocation>
            <FileDigest>I1/NFTYh/B8keozQiKJpHo49PRM=</FileDigest>
            <Url>http://dl.delivery.mp.microsoft.com/filestreamingservice/files/f4fbc1c0-984e-421c-8b55-7f239e9cd69f</Url>
          </FileLocation>
        </FileLocations>
      </GetExtendedUpdateInfo2Result>
    </GetExtendedUpdateInfo2Response>
  </s:Body>
</s:Envelope>
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/575928dd-8819-427e-96d4-d2d0b340e93a?P1=1661451999&P2=404&P3=2&P4=MYHea2UxSqouPj%2bNq5zmNN93QMY1e67q%2bNfxpmAeAuXVpqDbyHEi7%2bArQmrb5r5CFS4e16OHZMYt7AD15IT0Qw%3d%3d
Actual download started
Download complete
Deleting APPX to reduce disk usage
Removing package: Microsoft.MinecraftWindowsBeta_1.19.3022.0_x64__8wekyb3d8bbwe
Moving Minecraft data to: C:\Users\NOT SHOWING\AppData\Local\TmpMinecraftLocalState
Deployment progress: Processing 0%
Deployment progress: Processing 100%
Deployment done: Completed
Removal of package done: Microsoft.MinecraftWindowsBeta_1.19.3022.0_x64__8wekyb3d8bbwe
Registering package
Deployment failed: Deployment of package Microsoft.MinecraftWindowsBeta_1.19.3022.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
App re-register failed:
System.Exception: Deployment failed: Deployment of package Microsoft.MinecraftWindowsBeta_1.19.3022.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<DeploymentProgressWrapper>d__24.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<ReRegisterPackage>d__32.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass23_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 190
Registering package
Deployment failed: Deployment of package Microsoft.MinecraftWindowsBeta_1.19.3022.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
App re-register failed:
System.Exception: Deployment failed: Deployment of package Microsoft.MinecraftWindowsBeta_1.19.3022.0_x64__8wekyb3d8bbwe with package origin Unsigned failed because no valid license or sideloading policy could be applied. A developer license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration (http://go.microsoft.com/fwlink/?LinkId=231020) may be required.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<DeploymentProgressWrapper>d__24.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 230
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<ReRegisterPackage>d__32.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 324
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass23_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 190

**Comment by dktapps** [comment]
You need to enable Developer Mode in Windows, like it says on the README.

**Comment by GreatNate0509YT** [comment]
Thx I am a idiot for not checking readMe XD thanks so much I have used this before on win 10 but I installed win 11 so don’t have dev mode on anymore XD thx again
