### ISSUE TITLE
I got every time app registration failed

### ISSUE THREAD

**Issue by souhass** [MCMrARM/mc-w10-version-launcher#239]
BedrockLauncher.Exceptions.PackageRegistrationFailedException: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
 ---> System.Exception: Deployment failed: Windows cannot install package Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.Services.Store.Engagement" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 10.0.1610.0, along with this package to install. The frameworks with name "Microsoft.Services.Store.Engagement" currently installed are: {Microsoft.Services.Store.Engagement_10.0.19011.0_x64__8wekyb3d8bbwe Microsoft.Services.Store.Engagement_10.0.19011.0_x86__8wekyb3d8bbwe}
   at BedrockLauncher.Handlers.PackageHandler.DeploymentProgressWrapper(IAsyncOperationWithProgress`2 t) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 511
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 264
   --- End of inner exception stack trace ---
   at BedrockLauncher.Handlers.PackageHandler.RegisterPackage(MCVersion v) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 275
   at BedrockLauncher.Handlers.PackageHandler.InstallPackage(MCVersion v, String dirPath) in D:\a\BedrockLauncher\BedrockLauncher\BedrockLauncher.Backend\Handlers\PackageHandler.cs:line 83
* i try every single solution in internet and its not solved  pls help

**Comment by Imrglop** [comment]
I had this issue, did you try downloading minecraft from the store first?

**Comment by miqumi** [comment]
https://github.com/MCMrARM/mc-w10-version-launcher/issues/246
