### ISSUE TITLE
I didn't make a backup, the launcher overwrote my folder and deleted all my worlds, is there any backup folder or anything that I can do? 

### ISSUE THREAD

**Issue by willgamer1216** [MCMrARM/mc-w10-version-launcher#243]
My log file looks like this: 
Download start
GetDownloadUrl() response for updateIdentity 19477670-0d51-47de-99bd-8140dc6812ed, revision 1:
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:u="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
  <s:Header>
    <a:Action s:mustUnderstand="1">http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService/GetExtendedUpdateInfo2Response</a:Action>
    <a:RelatesTo>urn:uuid:5754a03d-d8d5-489f-b24d-efc31b3fd32d</a:RelatesTo>
    <o:Security s:mustUnderstand="1" xmlns:o="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
      <u:Timestamp u:Id="_0">
        <u:Created>2023-03-14T22:00:38.636Z</u:Created>
        <u:Expires>2023-03-14T22:05:38.636Z</u:Expires>
      </u:Timestamp>
    </o:Security>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <GetExtendedUpdateInfo2Response xmlns="http://www.microsoft.com/SoftwareDistribution/Server/ClientWebService">
      <GetExtendedUpdateInfo2Result>
        <FileLocations>
          <FileLocation>
            <FileDigest>s5G/asgUoawwMaGKEZq6wlhvB7c=</FileDigest>
            <Url>http://dl.delivery.mp.microsoft.com/filestreamingservice/files/0a5191ff-5cdc-4302-b3a3-7f39f273fa1c</Url>
          </FileLocation>
          <FileLocation>
            <FileDigest>uPK6N9xQzhDrQ608ny6ZWfsY1lo=</FileDigest>
            <Url>http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/efff7983-14fd-4f80-bbbd-459b05cf8809?P1=1678847599&amp;P2=404&amp;P3=2&amp;P4=RAbQGh2owfolUluT4hrIwvkPqXsQQU1Vk4A8aLezQbkZ1Q5SdZDvP1bJHNTQNxKU5%2b5X1QHA97%2fPAS%2b6K4%2fQPA%3d%3d</Url>
          </FileLocation>
        </FileLocations>
      </GetExtendedUpdateInfo2Result>
    </GetExtendedUpdateInfo2Response>
  </s:Body>
</s:Envelope>
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/efff7983-14fd-4f80-bbbd-459b05cf8809?P1=1678847599&P2=404&P3=2&P4=RAbQGh2owfolUluT4hrIwvkPqXsQQU1Vk4A8aLezQbkZ1Q5SdZDvP1bJHNTQNxKU5%2b5X1QHA97%2fPAS%2b6K4%2fQPA%3d%3d
Actual download started
Download complete
Deleting APPX to reduce disk usage
Removing package: Microsoft.MinecraftUWP_1.19.6301.0_x64__8wekyb3d8bbwe
Moving Minecraft data to: C:\Users\willm\AppData\Local\TmpMinecraftLocalState
Deployment progress: Processing 0%
Deployment progress: Processing 100%
Deployment done: Completed
Removal of package done: Microsoft.MinecraftUWP_1.19.6301.0_x64__8wekyb3d8bbwe
Registering package
Deployment progress: Processing 1%
Deployment progress: Processing 2%
Deployment progress: Processing 49%
Deployment progress: Processing 96%
Deployment progress: Processing 96%
Deployment progress: Processing 100%
Deployment done: Completed
App re-register done!
Moving backup Minecraft data to: C:\Users\willm\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState
App re-register failed:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\willm\AppData\Local\TmpMinecraftLocalState'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path)
   at MCLauncher.MainWindow.RestoreMove(String from, String to) in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 253
   at MCLauncher.MainWindow.RestoreMinecraftDataFromReinstall(String packageFamily) in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 280
   at MCLauncher.MainWindow.<ReRegisterPackage>d__32.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass23_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 190
Skipping package removal - same path: Microsoft.MinecraftUWP_1.19.6301.0_x64__8wekyb3d8bbwe C:\Games\MCLauncher\Minecraft-1.19.63.1
App launch finished!

**Comment by GreatNateDev** [comment]
Well I saw this in the log Moving Minecraft data to: C:\Users\willm\AppData\Local\TmpMinecraftLocalState
