### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by McMelonTV** [MCMrARM/mc-w10-version-launcher#25]
Download start
Download failed:
System.ArgumentException: Bad updateIdentity
   at MCLauncher.VersionDownloader.<Download>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass21_0.<<InvokeDownload>b__1>d.MoveNext()

**Comment by bullfrogberry** [comment]
Try downloading None beta versions. To download a Beta, as it come from the Microsoft store, you will need to sign up for the insider Beta in the "Xbox insiders hub" App under insiders tab under Minecraft. if you dont see it there you might need to look for an invite link. Currenty there are 2 beta programs and you can only have one active at a time. the Main one which offers most of the beta you probably want and the second is the new RTX beta for currently ONE version 1.15.8.0 which offers light effects Ray Tracing but only if you have a GPU that has the abilty such as a GTX2060 or greater

**Comment by Hellohi3654** [comment]
Download failed:
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at MCLauncher.VersionDownloader.<DownloadFile>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.VersionDownloader.<Download>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass21_0.<<InvokeDownload>b__1>d.MoveNext()

**Comment by Hellohi3654** [comment]
This is only a problem with betas using the insider hub to opt into betas works

**Comment by FreezzeYT** [comment]
But The problem occurs even at Full Release Version...
I m unable to download any Versions from Mc Launcher

**Comment by FreezzeYT** [comment]
> This is only a problem with betas using the insider hub to opt into betas wor

Problem occurs even with ful  version
