### ISSUE TITLE
'Unable to fetch download URL' for 1.20.71.1

### ISSUE THREAD

**Issue by G4z666** [MCMrARM/mc-w10-version-launcher#289]
it's been 3 days that i've been trying to download THIS SPECIFIC version but it keeps giving me errors, all the other ones work but this one, here's the logs:

Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/59fae4be-a5ba-4581-82e4-9561f01271f6?P1=1636527463&P2=404&P3=2&P4=CXb2syqWofpNsWTu6hvmJrSqNUBsQMjk1sy3hwGmyRxHGCqr2h0FPmR1Zps0gn%2flrISDfPgmvLFo7Hw9Et2b9g%3d%3d
Actual download started
Download failed:
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.BeginReadWithoutValidation(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.BeginRead(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<>n__0(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MCLauncher.VersionDownloader.<DownloadFile>d__3.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\VersionDownloader.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.VersionDownloader.<Download>d__6.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\VersionDownloader.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass30_0.<<InvokeDownload>b__1>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 286

**Comment by G4z666** [comment]
![Uploading Screenshot (98).png…]()

**Comment by DLazaridisGM** [comment]
https://github.com/MCMrARM/mc-w10-version-launcher/issues/288#issuecomment-2001993165
