### ISSUE TITLE
List download failed

### ISSUE THREAD

**Issue by jyooru** [MCMrARM/mc-w10-version-launcher#45]
List download failed:
```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.VersionList.<DownloadList>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<<-ctor>b__7_1>d.MoveNext()
```
![image](https://user-images.githubusercontent.com/63786778/86990793-bb740780-c1e0-11ea-887e-75ad0bf71232.png)

**Comment by Absence209** [comment]
Hey! Ive patched MCLauncher and uploaded it here. 
The problem was a bad certificate on the redirectors site but I bypassed it.
Download:
https://github.com/Absence209/MC-W10-LAUNCHER-PATCHED/releases/tag/0.1.2

**Comment by dktapps** [comment]
It would have been more helpful to make a PR instead of spooning it... Nobody can see what you did to fix it.

**Comment by jmkeol** [comment]
I agree with @dktapps here. GitHub is a place to contribute to one final product, not make derivatives and then publish them with no source.

ngl looks a little sketchy with the fact that you've reacted to your own post and haven't published the source. I'm also doubting that fix like this would add so many files and increase the file size by a few MB.

![image](https://user-images.githubusercontent.com/63786778/87018463-9e592c00-c214-11ea-9cf9-fe92e028fd5d.png)

**Comment by Absence209** [comment]
All I did was change the URL of the webpage it requests, idk why the file size is so big. Maybe because I switched the .net version to 4.8.

**Comment by DamianXAkuma** [comment]
i installed MCLAuncher and now my Minecraft Windows 10 is gone and i have to repay for it in the shop any help to fix this?

**Comment by jyooru** [comment]
This issue is stale.
