### ISSUE TITLE
Most of the times I've attempted to download a version, I've gotten this error message

### ISSUE THREAD

**Issue by ChillDawg5379** [MCMrARM/mc-w10-version-launcher#53]
System.IO.IOException: Unable to read data from the transport connection: The connection was closed.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MCLauncher.VersionDownloader.<DownloadFile>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.VersionDownloader.<Download>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass21_0.<<InvokeDownload>b__1>d.MoveNext()

Can anyone help?

**Comment by C0desr** [comment]
Hello, i think its because you need to enable developer mode on ur PC
here's a picture: 
https://user-images.githubusercontent.com/79480754/113301795-65467780-92cd-11eb-977a-b38b695a7b36.png
i really hope this helps have a Gooday sir,

**Comment by DamianXAkuma** [comment]
i installed MCLAuncher and now my Minecraft Windows 10 is gone and i have to repay for it in the shop any help to fix this?
