### ISSUE TITLE
App Re-Register Failed

### ISSUE THREAD

**Issue by c0d3rb0y** [MCMrARM/mc-w10-version-launcher#86]
System.IO.IOException: Access To The Path 'C:\Users\(my username)\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\' is denied.

What did I do wrong? It's probably already a solved issue, so I'm just asking here because I don't see it in the installation guide as an error that has steps to fix.

**Comment by c0d3rb0y** [comment]
could it be part of me having Minecraft Windows 10 Starter Pack edition from the store?

**Comment by c0d3rb0y** [comment]
never mind i fixed it by just opening it from the AppX files

**Comment by thanpixel** [comment]
I have the same issue. 

> never mind i fixed it by just opening it from the AppX files

I ran the "Minecraft.Windows.exe" file in the folder for the version and it keeps saying this. 
![image](https://user-images.githubusercontent.com/81921873/113515425-751ac180-9542-11eb-8ea0-38d8f3df0bdc.png)

**Comment by DamianXAkuma** [comment]
i installed MCLAuncher and now my Minecraft Windows 10 is gone and i have to repay for it in the shop any help to fix this?

**Comment by omuhu** [comment]
^ Same problem for me. The permissions for the folder look just fine, all users, including administrators have full access to LocalState. Any ideas on what to try next?

Download start
Resolved download link: http://tlu.dl.delivery.mp.microsoft.com/filestreamingservice/files/59fae4be-a5ba-4581-82e4-9561f01271f6?P1=1626411466&P2=404&P3=2&P4=LkKbMFAZO21gld5JF2rCWYx%2bLKCOV2FngCw21%2fkIMuYqnC6vzrcICXGxo9yZ4qe1tNaEGIyM6vtzOWo6%2f%2fChkA%3d%3d
Actual download started
Download complete
Removing package: Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe
Moving Minecraft data to: C:\Users\USERNAME\AppData\Local\TmpMinecraftLocalState
App re-register failed:
System.IO.IOException: Access to the path 'C:\Users\USERNAME\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at MCLauncher.MainWindow.BackupMinecraftDataForRemoval() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 172
   at MCLauncher.MainWindow.<RemovePackage>d__26.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 209
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MCLauncher.MainWindow.<ReRegisterPackage>d__29.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 235
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass20_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 112
Removing package: Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe
Moving Minecraft data to: C:\Users\USERNAME\AppData\Local\TmpMinecraftLocalState
App re-register failed:
System.IO.IOException: Access to the path 'C:\Users\USERNAME\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at MCLauncher.MainWindow.BackupMinecraftDataForRemoval() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 172
   at MCLauncher.MainWindow.<RemovePackage>d__26.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 209
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MCLauncher.MainWindow.<ReRegisterPackage>d__29.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 235
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass20_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 112
Removing package: Microsoft.MinecraftUWP_1.17.1004.0_x64__8wekyb3d8bbwe
Moving Minecraft data to: C:\Users\USERNAME\AppData\Local\TmpMinecraftLocalState
App re-register failed:
System.IO.IOException: Access to the path 'C:\Users\USERNAME\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at MCLauncher.MainWindow.BackupMinecraftDataForRemoval() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 172
   at MCLauncher.MainWindow.<RemovePackage>d__26.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 209
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MCLauncher.MainWindow.<ReRegisterPackage>d__29.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 235
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MCLauncher.MainWindow.<>c__DisplayClass20_0.<<InvokeLaunch>b__0>d.MoveNext() in C:\Users\dylan-work\Documents\projects\mc-w10-version-launcher\MCLauncher\MainWindow.xaml.cs:line 112

**Comment by dktapps** [comment]
Make sure you don't have another version of the game already running.

**Comment by omuhu** [comment]
Looks like the error message only shows up if I also have Minecraft installed in the regular location.

Basically, I can only use MCLauncher to install & run if I first uninstall normal Minecraft.
